// Auto-generierte Layer-Konfiguration
        {
          // Layer "Schweregrundnetz" (aus WMS)
          type: LayerType.swisstopoWMTS,
          label: t('lyr_ch.swisstopo.landesschwerenetz_label'),
          layer: 'ch.swisstopo.landesschwerenetz',
          maximumLevel: 18,
          visible: false,
          displayed: false,
          opacity: 0.7,
          queryType: 'geoadmin',
          geocatId: '95879cd4-e93d-4d4d-af57-4ec6731b9c97',
          legend: 'ch.swisstopo.landesschwerenetz',
        },
        {
          // Layer "Isostatische Anomalien 500" (aus WMTS)
          type: LayerType.swisstopoWMTS,
          label: t('lyr_ch.swisstopo.geologie-geodaesie-isostatische_anomalien_label'),
          layer: 'ch.swisstopo.geologie-geodaesie-isostatische_anomalien',
          maximumLevel: 18,
          visible: false,
          displayed: false,
          opacity: 0.7,
          queryType: 'geoadmin',
          geocatId: '7234896a-842c-4524-8710-5d900953cb1d',
          legend: 'ch.swisstopo.geologie-geodaesie-isostatische_anomalien',
        },
        {
          // Layer "Bouguer-Anomalien 500" (aus WMTS)
          type: LayerType.swisstopoWMTS,
          label: t('lyr_ch.swisstopo.geologie-geodaesie-bouguer_anomalien_label'),
          layer: 'ch.swisstopo.geologie-geodaesie-bouguer_anomalien',
          maximumLevel: 18,
          visible: false,
          displayed: false,
          opacity: 0.7,
          queryType: 'geoadmin',
          geocatId: '618c9697-129f-47c7-830a-7a256b4c2499',
          legend: 'ch.swisstopo.geologie-geodaesie-bouguer_anomalien',
        },
        {
          // Layer "Gravimetrischer Atlas 100" (aus WMTS)
          type: LayerType.swisstopoWMTS,
          label: t('lyr_ch.swisstopo.geologie-gravimetrischer_atlas_label'),
          layer: 'ch.swisstopo.geologie-gravimetrischer_atlas',
          maximumLevel: 18,
          visible: false,
          displayed: false,
          opacity: 0.7,
          queryType: 'geoadmin',
          geocatId: '732cb247-8307-4cc7-8c31-b1c505a94633',
          legend: 'ch.swisstopo.geologie-gravimetrischer_atlas',
        },
        {
          // Layer "Gravimetrische Messpunkte 100" (aus WMTS)
          type: LayerType.swisstopoWMTS,
          label: t('lyr_ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte_label'),
          layer: 'ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte',
          maximumLevel: 18,
          visible: false,
          displayed: false,
          opacity: 0.7,
          queryType: 'geoadmin',
          geocatId: '297a1958-3636-45af-a17c-e90120605132',
          legend: 'ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte',
        },
        {
          // Layer "Geoidmodell in CH1903" (aus WMTS)
          type: LayerType.swisstopoWMTS,
          label: t('lyr_ch.swisstopo.geoidmodell-ch1903_label'),
          layer: 'ch.swisstopo.geoidmodell-ch1903',
          maximumLevel: 18,
          visible: false,
          displayed: false,
          opacity: 0.7,
          queryType: 'geoadmin',
          geocatId: '2b20aece-5cb1-41f1-a618-7c6e1ff6a81b',
          legend: 'ch.swisstopo.geoidmodell-ch1903',
        },
